---
title: "Analysis of high-throughput sequencing data from NIH GEO database"
author: 
  - name: Taavi Päll
    affiliation: Department of Chemistry and Biotechnology, Tallinn University of Technology, Akadeemia tee 15, 12618 Tallinn, Estonia
    email: taavi.pall@ttu.ee
  - name: Tanel Tenson
    affiliation: Institute of Technology, University of Tartu, Nooruse 1, 50411, Tartu, Estonia
    email: tanel.tenson@ut.ee
  - name: Ülo Maiväli
    affiliation: Institute of Technology, University of Tartu, Nooruse 1, 50411, Tartu, Estonia
    email: ymaivali@gmail.com
    corresponding: true
abstract: >
  Assessing the quality of experiments, both directly and through replication attempts, is becoming a grave concern in biomedicine. 
  This is especially true in omics experiments, where thousands of independent measurements are done in parallel, with the understanding that only a small minority will probe scientifically meaningful effects – a state of affairs conductive to mistaking false positives for scientific discoveries. 
  A currently popular way to deal with false positives in omics is to calculate the Bayesian false-discovery rate (FDR) using, for the prior, the information present in the multitude of parallel measurements of a single omics experiment. 
  To this picture we add a simple method to calculate a retrospective power that is compatible with the FDR. 
  This allows to give a rich account of the quality and potential replicability of the results of almost any omics experiment. 
  As proof of concept we assessed the quality of the 9202 high-throughput sequencing experiments from Entrez GEO database.
bibliography: [references.bib, packages.bib]
cls: wlpeerj.cls
output: 
  Gmisc::docx_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.path = 'figures/', dev = c('pdf'))
library(tidyverse)
library(lubridate)
library(stringr)
library(magrittr)
library(formattable)
library(Biobase)
library(grid)
library(gridExtra)
```

```{r}
# Load helper functions
source("lib/helpers.R")
# Set panel label case
panel_label_case <- "upper"
```

```{r child='01_introduction.Rmd'}

```

```{r child='02_methods.Rmd'}

```

```{r child='03_results.Rmd'}

```


## References {-}
